// <auto-generated />
namespace Exam.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFileProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFileProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201609190534582_AddFileProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
