//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("EBasOrg")]
    public partial class EBasOrg
    {
        public EBasOrg()
        {
            this.EBasPersonInfoes = new HashSet<EBasPersonInfo>();
            this.EScoreFiles = new HashSet<EScoreFile>();
        }
    
        [Key]
        public string OrgCode { get; set; }
        public string OrgName { get; set; }
        public string ShortName { get; set; }
        public int SortCode { get; set; }
        public string StatusC { get; set; }
        public string ParentCode { get; set; }
        public int NextOrgNum { get; set; }
        public int NextOrgCode { get; set; }
        public string HierarchyCode { get; set; }
        public string HierarchyName { get; set; }
        public string Remark { get; set; }
        public string CreateByCode { get; set; }
        public string CreateByName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyByCode { get; set; }
        public string ModifyByName { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<EBasPersonInfo> EBasPersonInfoes { get; set; }
        public virtual ICollection<EScoreFile> EScoreFiles { get; set; }
    }
}
