//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("EScoreFileDetail")]
    public partial class EScoreFileDetail
    {
        public EScoreFileDetail()
        {
            this.EAbsentPersonInfoes = new HashSet<EAbsentPersonInfo>();
            this.EScoreProjectInputs = new HashSet<EScoreProjectInput>();
        }
    
        [Key]
        public string ScoreFileDetailId { get; set; }
        public string ScoreFileId { get; set; }
        public string ProfessionCode { get; set; }
        public string ProfessionName { get; set; }
        public decimal ProfessionAvgScore { get; set; }
        public int ProjectCount { get; set; }
        public int TakeTestPersonNum { get; set; }
        public int AbsentPersonNum { get; set; }
        public string Remark { get; set; }
        public string CreateByCode { get; set; }
        public string CreateByName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyByCode { get; set; }
        public string ModifyByName { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<EAbsentPersonInfo> EAbsentPersonInfoes { get; set; }
        public virtual EScoreFile EScoreFile { get; set; }
        public virtual ICollection<EScoreProjectInput> EScoreProjectInputs { get; set; }
    }
}
