//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ESysData")]
    public partial class ESysData
    {
        [Key]
        public string BusintypeId { get; set; }
        public string BusintypeCode { get; set; }
        public string BusinCode { get; set; }
        public string BusinName { get; set; }
        public string BusinLevel { get; set; }
        public string UpBusinCode { get; set; }
        public string BusinStatus { get; set; }
        public string Remark { get; set; }
        public string CreateByCode { get; set; }
        public string CreateByName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyByCode { get; set; }
        public string ModifyByName { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ESysDataType ESysDataType { get; set; }
    }
}
